server:
  port: ${PORT:8081}
logging:
  level:
    org.springframework.web: WARN
spring:
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
authorization:
  token: ${TOKEN}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8084}/eureka/
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
    secure-port-enabled: false
    non-secure-port-enabled: true
    secure-port: 443
    non-secure-port: 80
  password: ${EUREKA_PASSWORD:password}
ribbon:
  eager-load:
    enabled: true
security:
  user:
    password: ${eureka.password}
---
spring:
  profiles: local
eureka:
  instance:
    homePageUrl: http://${eureka.instance.hostname}:8081/
    non-secure-port: 8081
